-- Seeds the prohibited_keywords table with a multilingual profanity list, tagged
-- category='profanity' (distinct from admin-curated 'illegal_item' keywords).
-- Source: https://github.com/coffee-and-fun/google-profanity-words (MIT license),
-- English/Spanish/French/Arabic/Chinese lists combined and de-duplicated
-- case-insensitively (the table has a UNIQUE index on LOWER(keyword)).
--
-- Filtered out: bare words under 4 characters, and a short manual exclusion list
-- (anal, hell, crap, rape, cock, dick, balls, pawn, escort) whose plain-substring
-- match would collide with common marketplace words, e.g. 'rape' inside 'grape',
-- 'balls' inside 'baseballs', 'anal' inside 'analog'. Requires migration
-- 2026_07_19_keyword_category_ai_flags.sql (adds the category column) to run first.

INSERT INTO prohibited_keywords (keyword, category) VALUES
('2 girls 1 cup', 'profanity'),
('2g1c', 'profanity'),
('4r5e', 'profanity'),
('5h1t', 'profanity'),
('5hit', 'profanity'),
('a_s_s', 'profanity'),
('acrotomophilia', 'profanity'),
('alabama hot pocket', 'profanity'),
('alaskan pipeline', 'profanity'),
('anilingus', 'profanity'),
('anus', 'profanity'),
('apeshit', 'profanity'),
('ar5e', 'profanity'),
('arrse', 'profanity'),
('arse', 'profanity'),
('arsehole', 'profanity'),
('ass-fucker', 'profanity'),
('ass-hat', 'profanity'),
('ass-pirate', 'profanity'),
('assbag', 'profanity'),
('assbandit', 'profanity'),
('assbanger', 'profanity'),
('assbite', 'profanity'),
('assclown', 'profanity'),
('asscock', 'profanity'),
('asscracker', 'profanity'),
('asses', 'profanity'),
('assface', 'profanity'),
('assfucker', 'profanity'),
('assfukka', 'profanity'),
('assgoblin', 'profanity'),
('asshat', 'profanity'),
('asshead', 'profanity'),
('asshole', 'profanity'),
('assholes', 'profanity'),
('asshopper', 'profanity'),
('assjacker', 'profanity'),
('asslick', 'profanity'),
('asslicker', 'profanity'),
('assmonkey', 'profanity'),
('assmunch', 'profanity'),
('assmuncher', 'profanity'),
('asspirate', 'profanity'),
('assshole', 'profanity'),
('asssucker', 'profanity'),
('asswad', 'profanity'),
('asswhole', 'profanity'),
('asswipe', 'profanity'),
('auto erotic', 'profanity'),
('autoerotic', 'profanity'),
('b!tch', 'profanity'),
('b00bs', 'profanity'),
('b17ch', 'profanity'),
('b1tch', 'profanity'),
('babeland', 'profanity'),
('baby batter', 'profanity'),
('baby juice', 'profanity'),
('ball gag', 'profanity'),
('ball gravy', 'profanity'),
('ball kicking', 'profanity'),
('ball licking', 'profanity'),
('ball sack', 'profanity'),
('ball sucking', 'profanity'),
('ballbag', 'profanity'),
('ballsack', 'profanity'),
('bampot', 'profanity'),
('bangbros', 'profanity'),
('bareback', 'profanity'),
('barely legal', 'profanity'),
('barenaked', 'profanity'),
('bastard', 'profanity'),
('bastardo', 'profanity'),
('bastinado', 'profanity'),
('bdsm', 'profanity'),
('beaner', 'profanity'),
('beaners', 'profanity'),
('beastial', 'profanity'),
('beastiality', 'profanity'),
('beastility', 'profanity'),
('beaver cleaver', 'profanity'),
('beaver lips', 'profanity'),
('bellend', 'profanity'),
('bestial', 'profanity'),
('bestiality', 'profanity'),
('bi+ch', 'profanity'),
('biatch', 'profanity'),
('big black', 'profanity'),
('big breasts', 'profanity'),
('big knockers', 'profanity'),
('big tits', 'profanity'),
('bimbos', 'profanity'),
('birdlock', 'profanity'),
('bitch', 'profanity'),
('bitcher', 'profanity'),
('bitchers', 'profanity'),
('bitches', 'profanity'),
('bitchin', 'profanity'),
('bitching', 'profanity'),
('black cock', 'profanity'),
('blonde action', 'profanity'),
('blonde on blonde action', 'profanity'),
('bloody', 'profanity'),
('blow job', 'profanity'),
('blow your load', 'profanity'),
('blowjob', 'profanity'),
('blowjobs', 'profanity'),
('blue waffle', 'profanity'),
('blumpkin', 'profanity'),
('boiolas', 'profanity'),
('bollock', 'profanity'),
('bollocks', 'profanity'),
('bollok', 'profanity'),
('bollox', 'profanity'),
('bondage', 'profanity'),
('boner', 'profanity'),
('boob', 'profanity'),
('boobie', 'profanity'),
('boobs', 'profanity'),
('booobs', 'profanity'),
('boooobs', 'profanity'),
('booooobs', 'profanity'),
('booooooobs', 'profanity'),
('booty call', 'profanity'),
('breasts', 'profanity'),
('brown showers', 'profanity'),
('brunette action', 'profanity'),
('buceta', 'profanity'),
('bugger', 'profanity'),
('bukkake', 'profanity'),
('bulldyke', 'profanity'),
('bullet vibe', 'profanity'),
('bullshit', 'profanity'),
('bung hole', 'profanity'),
('bunghole', 'profanity'),
('bunny fucker', 'profanity'),
('busty', 'profanity'),
('butt', 'profanity'),
('butt-pirate', 'profanity'),
('buttcheeks', 'profanity'),
('butthole', 'profanity'),
('buttmunch', 'profanity'),
('buttplug', 'profanity'),
('c0ck', 'profanity'),
('c0cksucker', 'profanity'),
('camel toe', 'profanity'),
('camgirl', 'profanity'),
('camslut', 'profanity'),
('camwhore', 'profanity'),
('carpet muncher', 'profanity'),
('carpetmuncher', 'profanity'),
('cawk', 'profanity'),
('chinc', 'profanity'),
('chink', 'profanity'),
('choad', 'profanity'),
('chocolate rosebuds', 'profanity'),
('chode', 'profanity'),
('cipa', 'profanity'),
('circlejerk', 'profanity'),
('cl1t', 'profanity'),
('cleveland steamer', 'profanity'),
('clit', 'profanity'),
('clitface', 'profanity'),
('clitoris', 'profanity'),
('clits', 'profanity'),
('clover clamps', 'profanity'),
('clusterfuck', 'profanity'),
('cnut', 'profanity'),
('cock-sucker', 'profanity'),
('cockbite', 'profanity'),
('cockburger', 'profanity'),
('cockface', 'profanity'),
('cockhead', 'profanity'),
('cockjockey', 'profanity'),
('cockknoker', 'profanity'),
('cockmaster', 'profanity'),
('cockmongler', 'profanity'),
('cockmongruel', 'profanity'),
('cockmonkey', 'profanity'),
('cockmunch', 'profanity'),
('cockmuncher', 'profanity'),
('cocknose', 'profanity'),
('cocknugget', 'profanity'),
('cocks', 'profanity'),
('cockshit', 'profanity'),
('cocksmith', 'profanity'),
('cocksmoker', 'profanity'),
('cocksuck', 'profanity'),
('cocksucked', 'profanity'),
('cocksucker', 'profanity'),
('cocksucking', 'profanity'),
('cocksucks', 'profanity'),
('cocksuka', 'profanity'),
('cocksukka', 'profanity'),
('cokmuncher', 'profanity'),
('coksucka', 'profanity'),
('coochie', 'profanity'),
('coochy', 'profanity'),
('coon', 'profanity'),
('coons', 'profanity'),
('cooter', 'profanity'),
('coprolagnia', 'profanity'),
('coprophilia', 'profanity'),
('cornhole', 'profanity'),
('creampie', 'profanity'),
('cumbubble', 'profanity'),
('cumdumpster', 'profanity'),
('cumguzzler', 'profanity'),
('cumjockey', 'profanity'),
('cummer', 'profanity'),
('cumming', 'profanity'),
('cums', 'profanity'),
('cumshot', 'profanity'),
('cumslut', 'profanity'),
('cumtart', 'profanity'),
('cunilingus', 'profanity'),
('cunillingus', 'profanity'),
('cunnie', 'profanity'),
('cunnilingus', 'profanity'),
('cunt', 'profanity'),
('cuntface', 'profanity'),
('cunthole', 'profanity'),
('cuntlick', 'profanity'),
('cuntlicker', 'profanity'),
('cuntlicking', 'profanity'),
('cuntrag', 'profanity'),
('cunts', 'profanity'),
('cyalis', 'profanity'),
('cyberfuc', 'profanity'),
('cyberfuck', 'profanity'),
('cyberfucked', 'profanity'),
('cyberfucker', 'profanity'),
('cyberfuckers', 'profanity'),
('cyberfucking', 'profanity'),
('d1ck', 'profanity'),
('dammit', 'profanity'),
('damn', 'profanity'),
('darkie', 'profanity'),
('date rape', 'profanity'),
('daterape', 'profanity'),
('deep throat', 'profanity'),
('deepthroat', 'profanity'),
('dendrophilia', 'profanity'),
('dickbag', 'profanity'),
('dickbeater', 'profanity'),
('dickface', 'profanity'),
('dickhead', 'profanity'),
('dickhole', 'profanity'),
('dickjuice', 'profanity'),
('dickmilk', 'profanity'),
('dickmonger', 'profanity'),
('dickslap', 'profanity'),
('dicksucker', 'profanity'),
('dickwad', 'profanity'),
('dickweasel', 'profanity'),
('dickweed', 'profanity'),
('dickwod', 'profanity'),
('dike', 'profanity'),
('dildo', 'profanity'),
('dildos', 'profanity'),
('dingleberries', 'profanity'),
('dingleberry', 'profanity'),
('dink', 'profanity'),
('dinks', 'profanity'),
('dipshit', 'profanity'),
('dirsa', 'profanity'),
('dirty pillows', 'profanity'),
('dirty sanchez', 'profanity'),
('dlck', 'profanity'),
('dog style', 'profanity'),
('dog-fucker', 'profanity'),
('doggie style', 'profanity'),
('doggiestyle', 'profanity'),
('doggin', 'profanity'),
('dogging', 'profanity'),
('doggy style', 'profanity'),
('doggystyle', 'profanity'),
('dolcett', 'profanity'),
('domination', 'profanity'),
('dominatrix', 'profanity'),
('dommes', 'profanity'),
('donkey punch', 'profanity'),
('donkeyribber', 'profanity'),
('doochbag', 'profanity'),
('dookie', 'profanity'),
('doosh', 'profanity'),
('double dong', 'profanity'),
('double penetration', 'profanity'),
('douche', 'profanity'),
('douchebag', 'profanity'),
('dp action', 'profanity'),
('dry hump', 'profanity'),
('duche', 'profanity'),
('dumb', 'profanity'),
('dumbshit', 'profanity'),
('dumshit', 'profanity'),
('dvda', 'profanity'),
('dyke', 'profanity'),
('eat my ass', 'profanity'),
('ecchi', 'profanity'),
('ejaculate', 'profanity'),
('ejaculated', 'profanity'),
('ejaculates', 'profanity'),
('ejaculating', 'profanity'),
('ejaculatings', 'profanity'),
('ejaculation', 'profanity'),
('ejakulate', 'profanity'),
('erotic', 'profanity'),
('erotism', 'profanity'),
('eunuch', 'profanity'),
('f u c k', 'profanity'),
('f u c k e r', 'profanity'),
('f4nny', 'profanity'),
('f_u_c_k', 'profanity'),
('fagbag', 'profanity'),
('fagg', 'profanity'),
('fagging', 'profanity'),
('faggit', 'profanity'),
('faggitt', 'profanity'),
('faggot', 'profanity'),
('faggs', 'profanity'),
('fagot', 'profanity'),
('fagots', 'profanity'),
('fags', 'profanity'),
('fagtard', 'profanity'),
('fanny', 'profanity'),
('fannyflaps', 'profanity'),
('fannyfucker', 'profanity'),
('fanyy', 'profanity'),
('fart', 'profanity'),
('farted', 'profanity'),
('farting', 'profanity'),
('farty', 'profanity'),
('fatass', 'profanity'),
('fcuk', 'profanity'),
('fcuker', 'profanity'),
('fcuking', 'profanity'),
('fecal', 'profanity'),
('feck', 'profanity'),
('fecker', 'profanity'),
('felatio', 'profanity'),
('felch', 'profanity'),
('felching', 'profanity'),
('fellate', 'profanity'),
('fellatio', 'profanity'),
('feltch', 'profanity'),
('female squirting', 'profanity'),
('femdom', 'profanity'),
('figging', 'profanity'),
('fingerbang', 'profanity'),
('fingerfuck', 'profanity'),
('fingerfucked', 'profanity'),
('fingerfucker', 'profanity'),
('fingerfuckers', 'profanity'),
('fingerfucking', 'profanity'),
('fingerfucks', 'profanity'),
('fingering', 'profanity'),
('fistfuck', 'profanity'),
('fistfucked', 'profanity'),
('fistfucker', 'profanity'),
('fistfuckers', 'profanity'),
('fistfucking', 'profanity'),
('fistfuckings', 'profanity'),
('fistfucks', 'profanity'),
('fisting', 'profanity'),
('flamer', 'profanity'),
('flange', 'profanity'),
('fook', 'profanity'),
('fooker', 'profanity'),
('fool', 'profanity'),
('foot fetish', 'profanity'),
('footjob', 'profanity'),
('frotting', 'profanity'),
('fuck', 'profanity'),
('fuck buttons', 'profanity'),
('fucka', 'profanity'),
('fucked', 'profanity'),
('fucker', 'profanity'),
('fuckers', 'profanity'),
('fuckhead', 'profanity'),
('fuckheads', 'profanity'),
('fuckin', 'profanity'),
('fucking', 'profanity'),
('fuckings', 'profanity'),
('fuckingshitmotherfucker', 'profanity'),
('fuckme', 'profanity'),
('fucks', 'profanity'),
('fucktards', 'profanity'),
('fuckwhit', 'profanity'),
('fuckwit', 'profanity'),
('fudge packer', 'profanity'),
('fudgepacker', 'profanity'),
('fuker', 'profanity'),
('fukker', 'profanity'),
('fukkin', 'profanity'),
('fuks', 'profanity'),
('fukwhit', 'profanity'),
('fukwit', 'profanity'),
('futanari', 'profanity'),
('fux0r', 'profanity'),
('g-spot', 'profanity'),
('gang bang', 'profanity'),
('gangbang', 'profanity'),
('gangbanged', 'profanity'),
('gangbangs', 'profanity'),
('gay sex', 'profanity'),
('gayass', 'profanity'),
('gaybob', 'profanity'),
('gaydo', 'profanity'),
('gaylord', 'profanity'),
('gaysex', 'profanity'),
('gaytard', 'profanity'),
('gaywad', 'profanity'),
('genitals', 'profanity'),
('giant cock', 'profanity'),
('girl on', 'profanity'),
('girl on top', 'profanity'),
('girls gone wild', 'profanity'),
('goatcx', 'profanity'),
('goatse', 'profanity'),
('god damn', 'profanity'),
('god-dam', 'profanity'),
('god-damned', 'profanity'),
('goddamn', 'profanity'),
('goddamned', 'profanity'),
('gokkun', 'profanity'),
('golden shower', 'profanity'),
('goo girl', 'profanity'),
('gooch', 'profanity'),
('goodpoop', 'profanity'),
('gook', 'profanity'),
('goregasm', 'profanity'),
('gringo', 'profanity'),
('grope', 'profanity'),
('group sex', 'profanity'),
('guido', 'profanity'),
('guro', 'profanity'),
('hand job', 'profanity'),
('handjob', 'profanity'),
('hard core', 'profanity'),
('hardcore', 'profanity'),
('hardcoresex', 'profanity'),
('heeb', 'profanity'),
('hentai', 'profanity'),
('heshe', 'profanity'),
('hoar', 'profanity'),
('hoare', 'profanity'),
('hoer', 'profanity'),
('homo', 'profanity'),
('homoerotic', 'profanity'),
('honkey', 'profanity'),
('honky', 'profanity'),
('hooker', 'profanity'),
('hore', 'profanity'),
('horniest', 'profanity'),
('horny', 'profanity'),
('hot carl', 'profanity'),
('hot chick', 'profanity'),
('hotsex', 'profanity'),
('how to kill', 'profanity'),
('how to murder', 'profanity'),
('huge fat', 'profanity'),
('humping', 'profanity'),
('incest', 'profanity'),
('intercourse', 'profanity'),
('jack off', 'profanity'),
('jack-off', 'profanity'),
('jackass', 'profanity'),
('jackoff', 'profanity'),
('jail bait', 'profanity'),
('jailbait', 'profanity'),
('jelly donut', 'profanity'),
('jerk', 'profanity'),
('jerk off', 'profanity'),
('jerk-off', 'profanity'),
('jigaboo', 'profanity'),
('jiggaboo', 'profanity'),
('jiggerboo', 'profanity'),
('jism', 'profanity'),
('jizm', 'profanity'),
('jizz', 'profanity'),
('juggs', 'profanity'),
('kawk', 'profanity'),
('kike', 'profanity'),
('kinbaku', 'profanity'),
('kinkster', 'profanity'),
('kinky', 'profanity'),
('kiunt', 'profanity'),
('knob', 'profanity'),
('knobbing', 'profanity'),
('knobead', 'profanity'),
('knobed', 'profanity'),
('knobend', 'profanity'),
('knobhead', 'profanity'),
('knobjocky', 'profanity'),
('knobjokey', 'profanity'),
('kock', 'profanity'),
('kondum', 'profanity'),
('kondums', 'profanity'),
('kooch', 'profanity'),
('kootch', 'profanity'),
('kumer', 'profanity'),
('kummer', 'profanity'),
('kumming', 'profanity'),
('kums', 'profanity'),
('kunilingus', 'profanity'),
('kunt', 'profanity'),
('kyke', 'profanity'),
('l3i+ch', 'profanity'),
('l3itch', 'profanity'),
('labia', 'profanity'),
('leather restraint', 'profanity'),
('leather straight jacket', 'profanity'),
('lemon party', 'profanity'),
('lesbo', 'profanity'),
('lezzie', 'profanity'),
('lmfao', 'profanity'),
('lolita', 'profanity'),
('lovemaking', 'profanity'),
('lust', 'profanity'),
('lusting', 'profanity'),
('m0f0', 'profanity'),
('m0fo', 'profanity'),
('m45terbate', 'profanity'),
('ma5terb8', 'profanity'),
('ma5terbate', 'profanity'),
('make me come', 'profanity'),
('male squirting', 'profanity'),
('masochist', 'profanity'),
('master-bate', 'profanity'),
('masterb8', 'profanity'),
('masterbat*', 'profanity'),
('masterbat3', 'profanity'),
('masterbate', 'profanity'),
('masterbation', 'profanity'),
('masterbations', 'profanity'),
('masturbate', 'profanity'),
('menage a trois', 'profanity'),
('milf', 'profanity'),
('minge', 'profanity'),
('missionary position', 'profanity'),
('mo-fo', 'profanity'),
('mof0', 'profanity'),
('mofo', 'profanity'),
('mothafuck', 'profanity'),
('mothafucka', 'profanity'),
('mothafuckas', 'profanity'),
('mothafuckaz', 'profanity'),
('mothafucked', 'profanity'),
('mothafucker', 'profanity'),
('mothafuckers', 'profanity'),
('mothafuckin', 'profanity'),
('mothafucking', 'profanity'),
('mothafuckings', 'profanity'),
('mothafucks', 'profanity'),
('mother fucker', 'profanity'),
('motherfuck', 'profanity'),
('motherfucked', 'profanity'),
('motherfucker', 'profanity'),
('motherfuckers', 'profanity'),
('motherfuckin', 'profanity'),
('motherfucking', 'profanity'),
('motherfuckings', 'profanity'),
('motherfuckka', 'profanity'),
('motherfucks', 'profanity'),
('mound of venus', 'profanity'),
('mr hands', 'profanity'),
('muff', 'profanity'),
('muff diver', 'profanity'),
('muffdiver', 'profanity'),
('muffdiving', 'profanity'),
('mutha', 'profanity'),
('muthafecker', 'profanity'),
('muthafuckker', 'profanity'),
('muther', 'profanity'),
('mutherfucker', 'profanity'),
('n1gga', 'profanity'),
('n1gger', 'profanity'),
('nambla', 'profanity'),
('nawashi', 'profanity'),
('nazi', 'profanity'),
('negro', 'profanity'),
('neonazi', 'profanity'),
('nig nog', 'profanity'),
('nigg3r', 'profanity'),
('nigg4h', 'profanity'),
('nigga', 'profanity'),
('niggah', 'profanity'),
('niggas', 'profanity'),
('niggaz', 'profanity'),
('nigger', 'profanity'),
('niggers', 'profanity'),
('niglet', 'profanity'),
('nimphomania', 'profanity'),
('nipple', 'profanity'),
('nipples', 'profanity'),
('nob jokey', 'profanity'),
('nobhead', 'profanity'),
('nobjocky', 'profanity'),
('nobjokey', 'profanity'),
('nsfw images', 'profanity'),
('nude', 'profanity'),
('nudity', 'profanity'),
('numbnuts', 'profanity'),
('nutsack', 'profanity'),
('nympho', 'profanity'),
('nymphomania', 'profanity'),
('octopussy', 'profanity'),
('omorashi', 'profanity'),
('one cup two girls', 'profanity'),
('one guy one jar', 'profanity'),
('orgasim', 'profanity'),
('orgasims', 'profanity'),
('orgasm', 'profanity'),
('orgasms', 'profanity'),
('orgy', 'profanity'),
('p0rn', 'profanity'),
('paedophile', 'profanity'),
('paki', 'profanity'),
('panooch', 'profanity'),
('panties', 'profanity'),
('panty', 'profanity'),
('pecker', 'profanity'),
('peckerhead', 'profanity'),
('pedobear', 'profanity'),
('pedophile', 'profanity'),
('pegging', 'profanity'),
('penis', 'profanity'),
('penisfucker', 'profanity'),
('phone sex', 'profanity'),
('phonesex', 'profanity'),
('phuck', 'profanity'),
('phuk', 'profanity'),
('phuked', 'profanity'),
('phuking', 'profanity'),
('phukked', 'profanity'),
('phukking', 'profanity'),
('phuks', 'profanity'),
('phuq', 'profanity'),
('piece of shit', 'profanity'),
('pigfucker', 'profanity'),
('pimpis', 'profanity'),
('pises', 'profanity'),
('pisin', 'profanity'),
('pising', 'profanity'),
('pisof', 'profanity'),
('piss', 'profanity'),
('piss pig', 'profanity'),
('pissed', 'profanity'),
('pisser', 'profanity'),
('pissers', 'profanity'),
('pisses', 'profanity'),
('pissflap', 'profanity'),
('pissflaps', 'profanity'),
('pissin', 'profanity'),
('pissing', 'profanity'),
('pissoff', 'profanity'),
('pisspig', 'profanity'),
('playboy', 'profanity'),
('pleasure chest', 'profanity'),
('pole smoker', 'profanity'),
('polesmoker', 'profanity'),
('pollock', 'profanity'),
('ponyplay', 'profanity'),
('poof', 'profanity'),
('poon', 'profanity'),
('poonani', 'profanity'),
('poonany', 'profanity'),
('poontang', 'profanity'),
('poop', 'profanity'),
('poop chute', 'profanity'),
('poopchute', 'profanity'),
('porn', 'profanity'),
('porno', 'profanity'),
('pornography', 'profanity'),
('pornos', 'profanity'),
('prick', 'profanity'),
('pricks', 'profanity'),
('prince albert piercing', 'profanity'),
('pron', 'profanity'),
('pthc', 'profanity'),
('pube', 'profanity'),
('pubes', 'profanity'),
('punanny', 'profanity'),
('punany', 'profanity'),
('punta', 'profanity'),
('pusies', 'profanity'),
('pusse', 'profanity'),
('pussi', 'profanity'),
('pussies', 'profanity'),
('pussy', 'profanity'),
('pussylicking', 'profanity'),
('pussys', 'profanity'),
('pusy', 'profanity'),
('puto', 'profanity'),
('queaf', 'profanity'),
('queef', 'profanity'),
('queerbait', 'profanity'),
('queerhole', 'profanity'),
('quim', 'profanity'),
('raghead', 'profanity'),
('raging boner', 'profanity'),
('raping', 'profanity'),
('rapist', 'profanity'),
('rectum', 'profanity'),
('renob', 'profanity'),
('retard', 'profanity'),
('reverse cowgirl', 'profanity'),
('rimjaw', 'profanity'),
('rimjob', 'profanity'),
('rimming', 'profanity'),
('rosy palm', 'profanity'),
('rosy palm and her 5 sisters', 'profanity'),
('ruski', 'profanity'),
('rusty trombone', 'profanity'),
('s hit', 'profanity'),
('s.o.b.', 'profanity'),
('s_h_i_t', 'profanity'),
('sadism', 'profanity'),
('sadist', 'profanity'),
('santorum', 'profanity'),
('scat', 'profanity'),
('schlong', 'profanity'),
('scissoring', 'profanity'),
('screwing', 'profanity'),
('scroat', 'profanity'),
('scrote', 'profanity'),
('scrotum', 'profanity'),
('semen', 'profanity'),
('sexo', 'profanity'),
('sexy', 'profanity'),
('sh!+', 'profanity'),
('sh!t', 'profanity'),
('sh1t', 'profanity'),
('shag', 'profanity'),
('shagger', 'profanity'),
('shaggin', 'profanity'),
('shagging', 'profanity'),
('shaved beaver', 'profanity'),
('shaved pussy', 'profanity'),
('shemale', 'profanity'),
('shi+', 'profanity'),
('shibari', 'profanity'),
('shit', 'profanity'),
('shit-ass', 'profanity'),
('shit-bag', 'profanity'),
('shit-bagger', 'profanity'),
('shit-brain', 'profanity'),
('shit-breath', 'profanity'),
('shit-cunt', 'profanity'),
('shit-dick', 'profanity'),
('shit-eating', 'profanity'),
('shit-face', 'profanity'),
('shit-faced', 'profanity'),
('shit-fit', 'profanity'),
('shit-head', 'profanity'),
('shit-heel', 'profanity'),
('shit-hole', 'profanity'),
('shit-house', 'profanity'),
('shit-load', 'profanity'),
('shit-pot', 'profanity'),
('shit-spitter', 'profanity'),
('shit-stain', 'profanity'),
('shitass', 'profanity'),
('shitbag', 'profanity'),
('shitbagger', 'profanity'),
('shitblimp', 'profanity'),
('shitbrain', 'profanity'),
('shitbreath', 'profanity'),
('shitcunt', 'profanity'),
('shitdick', 'profanity'),
('shite', 'profanity'),
('shiteating', 'profanity'),
('shited', 'profanity'),
('shitey', 'profanity'),
('shitface', 'profanity'),
('shitfaced', 'profanity'),
('shitfit', 'profanity'),
('shitfuck', 'profanity'),
('shitfull', 'profanity'),
('shithead', 'profanity'),
('shitheel', 'profanity'),
('shithole', 'profanity'),
('shithouse', 'profanity'),
('shiting', 'profanity'),
('shitings', 'profanity'),
('shitload', 'profanity'),
('shitpot', 'profanity'),
('shits', 'profanity'),
('shitspitter', 'profanity'),
('shitstain', 'profanity'),
('shitted', 'profanity'),
('shitter', 'profanity'),
('shitters', 'profanity'),
('shittiest', 'profanity'),
('shitting', 'profanity'),
('shittings', 'profanity'),
('shitty', 'profanity'),
('shity', 'profanity'),
('shiz', 'profanity'),
('shiznit', 'profanity'),
('shota', 'profanity'),
('shrimping', 'profanity'),
('skank', 'profanity'),
('skeet', 'profanity'),
('slanteye', 'profanity'),
('slut', 'profanity'),
('slutbag', 'profanity'),
('sluts', 'profanity'),
('smeg', 'profanity'),
('smegma', 'profanity'),
('smut', 'profanity'),
('snatch', 'profanity'),
('snowballing', 'profanity'),
('sodomize', 'profanity'),
('sodomy', 'profanity'),
('son-of-a-bitch', 'profanity'),
('spac', 'profanity'),
('spic', 'profanity'),
('spick', 'profanity'),
('splooge', 'profanity'),
('splooge moose', 'profanity'),
('spooge', 'profanity'),
('spread legs', 'profanity'),
('spunk', 'profanity'),
('strap on', 'profanity'),
('strapon', 'profanity'),
('strappado', 'profanity'),
('strip club', 'profanity'),
('style doggy', 'profanity'),
('suck', 'profanity'),
('sucker', 'profanity'),
('sucks', 'profanity'),
('suicide girls', 'profanity'),
('sultry women', 'profanity'),
('swastika', 'profanity'),
('swinger', 'profanity'),
('t1tt1e5', 'profanity'),
('t1tties', 'profanity'),
('tainted love', 'profanity'),
('tard', 'profanity'),
('taste my', 'profanity'),
('tea bagging', 'profanity'),
('teets', 'profanity'),
('teez', 'profanity'),
('testical', 'profanity'),
('testicle', 'profanity'),
('threesome', 'profanity'),
('throating', 'profanity'),
('thundercunt', 'profanity'),
('tied up', 'profanity'),
('tight white', 'profanity'),
('titfuck', 'profanity'),
('tits', 'profanity'),
('titt', 'profanity'),
('tittie5', 'profanity'),
('tittiefucker', 'profanity'),
('titties', 'profanity'),
('titty', 'profanity'),
('tittyfuck', 'profanity'),
('tittywank', 'profanity'),
('titwank', 'profanity'),
('tongue in a', 'profanity'),
('topless', 'profanity'),
('tosser', 'profanity'),
('towelhead', 'profanity'),
('tranny', 'profanity'),
('tribadism', 'profanity'),
('tub girl', 'profanity'),
('tubgirl', 'profanity'),
('turd', 'profanity'),
('tushy', 'profanity'),
('tw4t', 'profanity'),
('twat', 'profanity'),
('twathead', 'profanity'),
('twatlips', 'profanity'),
('twatty', 'profanity'),
('twink', 'profanity'),
('twinkie', 'profanity'),
('two girls one cup', 'profanity'),
('twunt', 'profanity'),
('twunter', 'profanity'),
('undressing', 'profanity'),
('upskirt', 'profanity'),
('urethra play', 'profanity'),
('urophilia', 'profanity'),
('v14gra', 'profanity'),
('v1gra', 'profanity'),
('va-j-j', 'profanity'),
('vagina', 'profanity'),
('venus mound', 'profanity'),
('viagra', 'profanity'),
('vibrator', 'profanity'),
('violet wand', 'profanity'),
('vjayjay', 'profanity'),
('vorarephilia', 'profanity'),
('voyeur', 'profanity'),
('vulva', 'profanity'),
('w00se', 'profanity'),
('wang', 'profanity'),
('wank', 'profanity'),
('wanker', 'profanity'),
('wanky', 'profanity'),
('wet dream', 'profanity'),
('wetback', 'profanity'),
('white power', 'profanity'),
('whoar', 'profanity'),
('whore', 'profanity'),
('willies', 'profanity'),
('willy', 'profanity'),
('wrapping men', 'profanity'),
('wrinkled starfish', 'profanity'),
('xrated', 'profanity'),
('yaoi', 'profanity'),
('yellow showers', 'profanity'),
('yiffy', 'profanity'),
('zoophilia', 'profanity'),
('2 chicas 1 taza', 'profanity'),
('5 hit', 'profanity'),
('culo', 'profanity'),
('acrotomofilia', 'profanity'),
('bolsillo caliente de alabama', 'profanity'),
('oleoducto de alaska', 'profanity'),
('una mierda', 'profanity'),
('gilipollas', 'profanity'),
('follador de culo', 'profanity'),
('culo-gorro', 'profanity'),
('culo-pirata', 'profanity'),
('bolsa de culo', 'profanity'),
('bandido', 'profanity'),
('mordida', 'profanity'),
('payaso', 'profanity'),
('rompeculos', 'profanity'),
('culos', 'profanity'),
('cara de culo', 'profanity'),
('hijo de puta', 'profanity'),
('enculada', 'profanity'),
('asno duende', 'profanity'),
('idiota', 'profanity'),
('Estúpido', 'profanity'),
('imbéciles', 'profanity'),
('asaltante', 'profanity'),
('ladrón de traseros', 'profanity'),
('lamer el culo', 'profanity'),
('lameculos', 'profanity'),
('culo mono', 'profanity'),
('mascador de culos', 'profanity'),
('aspirar', 'profanity'),
('chupador de culos', 'profanity'),
('auto erótico', 'profanity'),
('autoerotico', 'profanity'),
('perra', 'profanity'),
('masa para bebes', 'profanity'),
('jugo de bebe', 'profanity'),
('mordaza de bola', 'profanity'),
('salsa de bolas', 'profanity'),
('patear la pelota', 'profanity'),
('pelota lamiendo', 'profanity'),
('saco de pelota', 'profanity'),
('chupando bolas', 'profanity'),
('bolsa de pelota', 'profanity'),
('pelotas', 'profanity'),
('saco de bolas', 'profanity'),
('bang bros', 'profanity'),
('a pelo', 'profanity'),
('apenas legal', 'profanity'),
('desnudo', 'profanity'),
('frijol', 'profanity'),
('frijoles', 'profanity'),
('bestialidad', 'profanity'),
('cuchillo de castor', 'profanity'),
('labios de castor', 'profanity'),
('campana', 'profanity'),
('grande y negro', 'profanity'),
('pechos grandes', 'profanity'),
('grandes aldabas', 'profanity'),
('grandes tetas', 'profanity'),
('tontas', 'profanity'),
('cerradura de pájaro', 'profanity'),
('perras', 'profanity'),
('quejándose', 'profanity'),
('gallo negro', 'profanity'),
('acción rubia', 'profanity'),
('rubia sobre rubia acción', 'profanity'),
('sangriento', 'profanity'),
('mamada', 'profanity'),
('sopla tu carga', 'profanity'),
('mamadas', 'profanity'),
('gofre azul', 'profanity'),
('tonto', 'profanity'),
('mierda', 'profanity'),
('cojones', 'profanity'),
('esclavitud', 'profanity'),
('metedura de pata', 'profanity'),
('teta', 'profanity'),
('bobo', 'profanity'),
('tetas', 'profanity'),
('llamada de botín', 'profanity'),
('senos', 'profanity'),
('duchas marrones', 'profanity'),
('acción morena', 'profanity'),
('bullyke', 'profanity'),
('vibra de bala', 'profanity'),
('agujero de tapón', 'profanity'),
('boca de tonel', 'profanity'),
('conejito hijo de puta', 'profanity'),
('tetona', 'profanity'),
('culata', 'profanity'),
('trasero-pirata', 'profanity'),
('nalgas', 'profanity'),
('ojete', 'profanity'),
('masticar trasero', 'profanity'),
('verga', 'profanity'),
('dedo de camello', 'profanity'),
('puta de la cam', 'profanity'),
('masticador de alfombras', 'profanity'),
('mascador de alfombras', 'profanity'),
('graznar', 'profanity'),
('chinchilla', 'profanity'),
('grieta', 'profanity'),
('capullos de rosa de chocolate', 'profanity'),
('cipá', 'profanity'),
('círculo idiota', 'profanity'),
('vapor de cleveland', 'profanity'),
('clítoris', 'profanity'),
('abrazaderas de trébol', 'profanity'),
('racimo de mierda', 'profanity'),
('nuez', 'profanity'),
('polla', 'profanity'),
('chupapollas', 'profanity'),
('mordedura de gallo', 'profanity'),
('hamburguesa', 'profanity'),
('cara de gallo', 'profanity'),
('cabeza de gallo', 'profanity'),
('jockey', 'profanity'),
('aldaba', 'profanity'),
('maestro de gallos', 'profanity'),
('traficante de gallos', 'profanity'),
('mono gallo', 'profanity'),
('gallo', 'profanity'),
('comepollas', 'profanity'),
('nariz de gallo', 'profanity'),
('pepita', 'profanity'),
('pollas', 'profanity'),
('herrero', 'profanity'),
('fumador de pollas', 'profanity'),
('mamar', 'profanity'),
('mamando', 'profanity'),
('pollasuka', 'profanity'),
('coca', 'profanity'),
('cocinando', 'profanity'),
('chulo', 'profanity'),
('mapache', 'profanity'),
('mapaches', 'profanity'),
('coprofilia', 'profanity'),
('timonel', 'profanity'),
('tonterías', 'profanity'),
('cremita', 'profanity'),
('desmoronamiento', 'profanity'),
('basurero', 'profanity'),
('devorador de semen', 'profanity'),
('corrida', 'profanity'),
('correrse', 'profanity'),
('se corre', 'profanity'),
('zorra', 'profanity'),
('coño', 'profanity'),
('cara de chocho', 'profanity'),
('lamer el coño', 'profanity'),
('lamecoños', 'profanity'),
('lamiendo coños', 'profanity'),
('coños', 'profanity'),
('cibernético', 'profanity'),
('ciberfuckers', 'profanity'),
('maldita sea', 'profanity'),
('maldición', 'profanity'),
('moreno', 'profanity'),
('violación en una cita', 'profanity'),
('cita', 'profanity'),
('Garganta profunda', 'profanity'),
('dendrofilia', 'profanity'),
('bolsa de pene', 'profanity'),
('batidor de pollas', 'profanity'),
('cara de pene', 'profanity'),
('pendejo', 'profanity'),
('jugo de polla', 'profanity'),
('dickleche', 'profanity'),
('traficante de pollas', 'profanity'),
('bofetada', 'profanity'),
('comadreja', 'profanity'),
('dique', 'profanity'),
('consolador', 'profanity'),
('consoladores', 'profanity'),
('moras', 'profanity'),
('zarzamora', 'profanity'),
('borrachos', 'profanity'),
('dirección', 'profanity'),
('almohadas sucias', 'profanity'),
('sucio sanchez', 'profanity'),
('estilo perro', 'profanity'),
('follador de perros', 'profanity'),
('estilo perrito', 'profanity'),
('persiguiendo', 'profanity'),
('a cuatro patas', 'profanity'),
('dominación', 'profanity'),
('dominatriz', 'profanity'),
('domos', 'profanity'),
('ponche de burro', 'profanity'),
('burro', 'profanity'),
('bolsa de basura', 'profanity'),
('chiflado', 'profanity'),
('doble polla', 'profanity'),
('doble penetración', 'profanity'),
('ducha', 'profanity'),
('acción doble penetración', 'profanity'),
('joroba seca', 'profanity'),
('estupideces', 'profanity'),
('come mi culo', 'profanity'),
('eyacular', 'profanity'),
('eyaculado', 'profanity'),
('eyacula', 'profanity'),
('eyaculando', 'profanity'),
('eyaculación', 'profanity'),
('erótico', 'profanity'),
('erotismo', 'profanity'),
('escolta', 'profanity'),
('eunuco', 'profanity'),
('Cabron', 'profanity'),
('maricón', 'profanity'),
('marica', 'profanity'),
('mariconear', 'profanity'),
('maricas', 'profanity'),
('pedo', 'profanity'),
('tirado un pedo', 'profanity'),
('tirando pedos', 'profanity'),
('gordo', 'profanity'),
('joder', 'profanity'),
('felación', 'profanity'),
('fieltro', 'profanity'),
('chorros femeninos', 'profanity'),
('dominación femenina', 'profanity'),
('fijándose', 'profanity'),
('pistola con la mano', 'profanity'),
('follar con los dedos', 'profanity'),
('dedo follado', 'profanity'),
('follador de dedos', 'profanity'),
('folladores de dedos', 'profanity'),
('follando con los dedos', 'profanity'),
('folla con los dedos', 'profanity'),
('digitación', 'profanity'),
('follar con el puño', 'profanity'),
('puño follado', 'profanity'),
('follador de puños', 'profanity'),
('folladores de puños', 'profanity'),
('follando con el puño', 'profanity'),
('follando con los puños', 'profanity'),
('folla con los puños', 'profanity'),
('puño', 'profanity'),
('lanzallamas', 'profanity'),
('brida', 'profanity'),
('buscar', 'profanity'),
('buscador de', 'profanity'),
('fetichismo de pies', 'profanity'),
('paja de pies', 'profanity'),
('frotándose', 'profanity'),
('botones de mierda', 'profanity'),
('jodido', 'profanity'),
('hijos de puta', 'profanity'),
('imbécil', 'profanity'),
('maldito', 'profanity'),
('malditos', 'profanity'),
('mierdamierdahijo de puta', 'profanity'),
('fóllame', 'profanity'),
('folla', 'profanity'),
('cabrones', 'profanity'),
('empaquetador de dulces', 'profanity'),
('empacador de chocolate', 'profanity'),
('Punto G', 'profanity'),
('orgia', 'profanity'),
('orgias', 'profanity'),
('sexo gay', 'profanity'),
('culo gay', 'profanity'),
('señor gay', 'profanity'),
('tardo gay', 'profanity'),
('genitales', 'profanity'),
('polla gigante', 'profanity'),
('chica en', 'profanity'),
('niña en la cima', 'profanity'),
('las chicas se volvieron locas', 'profanity'),
('cabracx', 'profanity'),
('cabra', 'profanity'),
('baño de oro', 'profanity'),
('buena chica', 'profanity'),
('buena caca', 'profanity'),
('bien', 'profanity'),
('goregasmo', 'profanity'),
('ir a tientas', 'profanity'),
('sexo en grupo', 'profanity'),
('trabajo manual', 'profanity'),
('paja', 'profanity'),
('núcleo duro', 'profanity'),
('duro', 'profanity'),
('sexo duro', 'profanity'),
('infierno', 'profanity'),
('el ella', 'profanity'),
('azada', 'profanity'),
('puta', 'profanity'),
('homoerótico', 'profanity'),
('cariño', 'profanity'),
('horre', 'profanity'),
('más caliente', 'profanity'),
('córneo', 'profanity'),
('caliente carl', 'profanity'),
('chica caliente', 'profanity'),
('sexo caliente', 'profanity'),
('como matar', 'profanity'),
('como asesinar', 'profanity'),
('gordo enorme', 'profanity'),
('follando', 'profanity'),
('incesto', 'profanity'),
('coito', 'profanity'),
('masturbar', 'profanity'),
('cebo de la cárcel', 'profanity'),
('japón', 'profanity'),
('rosquilla de gelatina', 'profanity'),
('hacerse una paja', 'profanity'),
('masturbarse', 'profanity'),
('esperma', 'profanity'),
('pozo', 'profanity'),
('pervertido', 'profanity'),
('rizado', 'profanity'),
('mando', 'profanity'),
('perillas', 'profanity'),
('nudoso', 'profanity'),
('perilla', 'profanity'),
('cabeza de chorlito', 'profanity'),
('bromista', 'profanity'),
('golpe', 'profanity'),
('chiflar', 'profanity'),
('coquetear', 'profanity'),
('kúmer', 'profanity'),
('picazón', 'profanity'),
('labios', 'profanity'),
('restricción de cuero', 'profanity'),
('chaqueta recta de cuero', 'profanity'),
('fiesta de limon', 'profanity'),
('lesbiana', 'profanity'),
('haciendo el amor', 'profanity'),
('lujuria', 'profanity'),
('codiciando', 'profanity'),
('m45terbato', 'profanity'),
('ma5terbato', 'profanity'),
('Hazme llegar', 'profanity'),
('chorros masculinos', 'profanity'),
('masoquista', 'profanity'),
('maestro-bate', 'profanity'),
('maestrob8', 'profanity'),
('maestro murciélago*', 'profanity'),
('masterbación', 'profanity'),
('masterbaciones', 'profanity'),
('menaje', 'profanity'),
('merde', 'profanity'),
('putain', 'profanity'),
('connard', 'profanity'),
('connasse', 'profanity'),
('salope', 'profanity'),
('salaud', 'profanity'),
('bordel', 'profanity'),
('chiant', 'profanity'),
('foutre', 'profanity'),
('enculé', 'profanity'),
('enfoiré', 'profanity'),
('fils de pute', 'profanity'),
('casse‑toi', 'profanity'),
('ferme ta gueule', 'profanity'),
('va te faire foutre', 'profanity'),
('ta gueule', 'profanity'),
('pute', 'profanity'),
('couille', 'profanity'),
('couillon', 'profanity'),
('bâtard', 'profanity'),
('gros con', 'profanity'),
('trou du cul', 'profanity'),
('لعنة', 'profanity'),
('اللعنة', 'profanity'),
('خراء', 'profanity'),
('قحبة', 'profanity'),
('شرموطة', 'profanity'),
('ابن زنا', 'profanity'),
('ابن حرام', 'profanity'),
('يا كلب', 'profanity'),
('حمار', 'profanity'),
('يا حمار', 'profanity'),
('يا ابن الكلب', 'profanity'),
('يلعن أبوك', 'profanity'),
('يلعن شكلك', 'profanity'),
('تفو عليك', 'profanity'),
('انقلع', 'profanity'),
('اخرس', 'profanity'),
('去你妈的', 'profanity'),
('狗娘养的', 'profanity')
ON CONFLICT (lower(keyword)) DO NOTHING;

-- Verify
SELECT category, COUNT(*) FROM prohibited_keywords GROUP BY category;
