upstream backend {
    server backend:8000;
}

upstream bidding_engine {
    server bidding-engine:8001;
}

upstream recommendation_engine {
    server recommendation-engine:8002;
}

server {
    listen 80;
    server_name localhost;

    # Backend Core & Swagger Docs
    location /v1.0.0/ {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Bidding Engine REST & Swagger Docs
    location /v1.0.0/bids/ {
        proxy_pass http://bidding_engine;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # WebSockets
    location /ws/ {
        proxy_pass http://bidding_engine;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    # Recommendation Engine REST & Swagger Docs
    location /v1.0.0/recs/ {
        proxy_pass http://recommendation_engine;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Also route /trending specifically to Recommendation Engine
    location /v1.0.0/trending {
        proxy_pass http://recommendation_engine/v1.0.0/recs/trending;
        proxy_set_header Host $host;
    }

    location /health {
        return 200 '{"status":"UP"}';
        add_header Content-Type application/json;
    }
}
